### ISSUE TITLE
error when running the tool

### ISSUE THREAD

**Issue by Cache-Bounty** [x0rr-dan/s1c0n#2]
% python3 sicon.py -u domo.com
Traceback (most recent call last):
  File "/Users/Pam/Desktop/sicon.py", line 2, in <module>
    from turtle import color
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/turtle.py", line 107, in <module>
    import tkinter as TK
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

**Comment by x0rr-dan** [comment]
i have no clue for this
maybe someone can help with this problem

**Comment by doncalli** [comment]
Cache-Bounty...You will need to install **python3-tk** if you don't already have it

**Comment by Cache-Bounty** [comment]
MYDesktop % **python3 sicon.py -u domo.com**     

	   [!] Error on import No module named 'nmap'
[!] nmap is missing, Please run me with sudo to install nmap

Thanks now I am getting error:


MYDesktop % **sudo python3 sicon.py -u domo.com**

	   [!] Error on import No module named 'nmap'
[!] nmap missing
[!] installing nmap
Traceback (most recent call last):
  File "/Users/hacker/Desktop/sicon.py", line 51, in <module>
    check(tool)
  File "/Users/hacker/Desktop/sicon.py", line 45, in check
    time.sleep(0.2)
NameError: name 'time' is not defined

**Comment by doncalli** [comment]
root-x-krypt0n-x, 
hello there. I initially HAD issues running your script if running with python3. so I made some adjustments to make it work.
1. had to install python3.nmap (I am running python 3.10 in my environment). 
Reference https://pypi.org/project/python3-nmap/
2. had to compile and install the latest nmap (7.20) from nmap.org (now referred to "nmap3")
3. had to install python3-tk for the tklinter issue reported earlier

With these changes, the script then managed to run to an extent

Then based on https://pypi.org/project/python3-nmap/, I made some further adjustments on the sicon.py script to get the script into referencing "nmap3" as a python module. I have pasted the FULL modified script below with comments

## 1.1: importing dependencies
from turtle import color


try:
	from os import path, system, getcwd
	import os.path
	import subprocess
	import nmap3
	import json
	import sys
	import time
except ImportError as error:
	print("\n\t   [!] Error on import", error)

## 1.2: defining classes & functions:
class Colors:
	RESET     = "\33[0m"
	BOLD      = "\33[1m"
	RED       = "\33[31m"
	GREEN     = "\33[32m"
	YELLOW    = "\33[33m"

## 1.4 checking dependecies tools

def check(tool):
  if os.path.exists("/usr/bin/" + tool) == True:
	  print(Colors.GREEN + Colors.BOLD + "[*] " + tool +  " exist" + Colors.RESET)
	  time.sleep(0.2)
	  pass

  elif os.path.exists("/usr/bin" + tool) == False:
	  # checking user privileges
	  user = os.getuid()
	  
	  if user == 0:
		  pass

	  else:
		  print(Colors.RED + Colors.BOLD + "[!] " + tool + " is missing, Please run me with sudo to install " + tool + Colors.RESET)
		  exit()
	  # installing missing requirements
	  print(Colors.RED + Colors.BOLD + "[!] " + tool + " missing" + Colors.RESET)
	  print(Colors.RED + Colors.BOLD + "[!] installing " + tool + Colors.RESET)
	  time.sleep(0.2)
	  system("apt install "+ tool + " -y")

# requirements
list_tool = ['nmap','wafw00f','sublist3r','subfinder','assetfinder','amass','dirsearch','httprobe']
for tool in list_tool:
  check(tool)
  pass

def break_and_help():
	print("\n\t   [?] Usage example: sicon -u target.com")
	exit()

def remove_list_files(extension):
	system("rm -rf .list*.%s" % extension)



## 1.4: preparing everything
saving_path = getcwd() + "/"
#port_scan = nmap.PortScanner()..........................for NMAP 
nmap = nmap3.nmap()

## 1.5: "welcome" screen
system("clear")
print(Colors.GREEN + Colors.BOLD + """
\t          ┏━┓╺┓ ┏━╸┏━┓┏┓╻
\t          ┗━┓ ┃ ┃  ┃┃┃┃┗┫
\t          ┗━┛╺┻╸┗━╸┗━┛╹ ╹
                
                    Simple Recon
                Coded by """ + Colors.RESET + Colors.RED + Colors.BOLD + """UnknownSec666""" + Colors.RESET + Colors.GREEN + Colors.BOLD + """
		   Thanks to:""" + Colors.RED + Colors.BOLD + """ Jeager""" +
Colors.RESET)

## 1.6: getting started
command_arguments = sys.argv[1:]

if (len(command_arguments) > 0):
	flag = command_arguments[0].upper()

	if flag == "-U" or flag == "--URL":
		URL_TARGET = command_arguments[1]

	else:
		break_and_help()

else:
	break_and_help()



## 2.0: Starting recon phase:
print(Colors.BOLD + Colors.GREEN + "\n\t[*] Starting recon on %s:" % URL_TARGET + Colors.RESET)

## 2.1: Detect WAF using wafw00f:
# convert to domain using httprobe
get_host   = subprocess.check_output(("echo %s | httprobe -prefer-https" % URL_TARGET), shell=True, text=True)
detect_waf = subprocess.check_output(("wafw00f %s > /dev/null" % get_host), shell=True, text=True)

if ("is behind" in detect_waf):
	## has some WAF
	processed_string = detect_waf[detect_waf.find("is behind"):]
	pre_parser  = processed_string.find("\x1b[1;96m") # process to get valuable results only
	post_parser = processed_string.find("\x1b[0m")
	which_waf   = processed_string[pre_parser:post_parser] # don't include color codes

	print(Colors.BOLD + Colors.GREEN + "\n\t  [+] WAF: DETECTED [ %s ]" % which_waf + Colors.RESET)

elif ("No WAF detected" in detect_waf):
	print(Colors.BOLD + Colors.YELLOW + "\n\t  [+] WAF: NOT DETECTED" + Colors.RESET)

else:
	print(Colors.BOLD + Colors.RED  + "\n\t  [!] FAIL TO DETECT WAF" + Colors.RESET)

### 2.2: Scanning ports using nmap
# run NMAP and filter results using GREP 
system("nmap %s -o .list_NMAP.txt > /dev/null" % URL_TARGET)..............Change made here
system("cat .list_NMAP.txt | grep open > .list_PORTS.txt")

# open file we just created
with open(".list_PORTS.txt", encoding="utf-8") as file:
	ports_list = file.read().splitlines()

# remove files we just created
remove_list_files("txt")

print(Colors.BOLD + Colors.GREEN + "\n\t  [+] OPENED PORTS: %s" % len(ports_list) + Colors.RESET)

for p in ports_list:
	print(Colors.RESET + "\t    " + Colors.GREEN + "-> " + Colors.RESET + Colors.BOLD + p)

### 2.3: Getting subdomains
# this process might take a while, we'll use different scripts for that
system("subfinder -d %s -o .list_subfinder.txt -silent > /dev/null" % URL_TARGET)
system("sublist3r -d %s -o .list_sublist3r.txt > /dev/null" % URL_TARGET)
system("assetfinder %s > .list_assetfinder.txt" % URL_TARGET)
system("amass enum -d %s -o .list_amass.txt -silent" % URL_TARGET)

# concat every output into one file
system("cat .list*.txt > .list_subdomains.txt")

# open "general" file
with open(".list_subdomains.txt", encoding="utf-8") as file:
	subdomain_raw_list = file.read().splitlines()

# drop duplicates
subdomain_list = set(subdomain_raw_list)

remove_list_files("txt")

print(Colors.BOLD + Colors.GREEN + "\n\t  [+] SUBDOMAINS DETECTED: %s" % len(subdomain_list) + Colors.RESET)

for s in subdomain_list:

	# perform quick port scan using nmap
	#quick_scan = port_scan.scan(hosts=s, arguments="-F") ..........for NMAP
	quick_scan = nmap.scan(hosts=s, arguments="-F")
	host = list(quick_scan["scan"].keys())
	
	if (len(host) > 0):
		# tcp ports were found
		tcp_open = str(list(quick_scan["scan"][host[0]]["tcp"].keys()))
		print(Colors.RESET + Colors.GREEN + "\t    -> " + Colors.RESET + Colors.BOLD + s +
										" | " +  Colors.GREEN + tcp_open + Colors.RESET)
	else:
		# port scan failed
		print(Colors.RESET + Colors.GREEN + "\t    -> " + Colors.RESET + Colors.BOLD + s +
										" | " +  Colors.RED + "FAIL MAYBE HOST DIED" + Colors.RESET)

### 2.4: Bruteforcing json_directory:
system("dirsearch -u {} -o {} --format=json > /dev/null".format(URL_TARGET, (saving_path + ".list_json_directory.json")))

with open(".list_json_directory.json", encoding="utf-8") as file:
	json_directory = json.load(file)
	
remove_list_files("json")

host      = str( list(json_directory["results"][0].keys())[0] )
directory = json_directory["results"][0][host]

dir_list = []
for d in directory:
	path = d["path"]
	status = d["status"]

	# drop other codes
	if (status == 200 or status == 403):
		dir_list.append([status, path])

sorted_directories = sorted(dir_list)

print(Colors.BOLD + Colors.GREEN + "\n\t  [+] DIRECTORIES: %s" % len(sorted_directories) + Colors.RESET)

for d in sorted_directories:

	format_host = get_host.replace("\n", "")

	if (d[0] == 200):
		# green alert
		print(Colors.GREEN + "\t    -> " + Colors.RESET + Colors.GREEN
				+ str(d[0]) + Colors.RESET + " | " +  Colors.BOLD + format_host + d[1] + Colors.RESET)
	
	elif (d[0] == 403):
		print(Colors.GREEN + "\t    -> " + Colors.RESET + Colors.YELLOW 
				+ str(d[0]) + Colors.RESET + " | " +  Colors.BOLD + format_host + d[1] + Colors.RESET)

I can send you the file if you provide me with a place to upload to.

#######List of adjustment made to sicon.py#############

1.
Basically I had to import nmap3 (instead of nmap) and reference it below:
try:
	from os import path, system, getcwd
	import os.path
	import subprocess
	**import nmap3**
	import json
	import sys
	import time
## 1.4: preparing everything
saving_path = getcwd() + "/"
#port_scan = nmap.PortScanner()..........................for NMAP 
nmap = nmap3.nmap()

2.
Then i made an adjustment here:

### 2.2: Scanning ports using nmap
# run NMAP and filter results using GREP 
system("nmap %s -o .list_NMAP.txt > /dev/null" % URL_TARGET)..............Change made here
system("cat .list_NMAP.txt | grep open > .list_PORTS.txt")

3.
The final adjustment was made here:
for s in subdomain_list:

	# perform quick port scan using nmap
	#quick_scan = port_scan.scan(hosts=s, arguments="-F") ..........for NMAP
	quick_scan = nmap.scan(hosts=s, arguments="-F")
	host = list(quick_scan["scan"].keys())

The result of the adjustments is the adjusted script now running with:
1. the WAF scan module working
2. the "Opened Ports" scan module working
However I am running into issues where I see the sub-domain scan FAIL
My investigation reveals that the **.list_amass.txt** is NOT being created by the script (see script line below) in the directory that the script is being run. The other files ARE BEING CREATED

system("amass enum -d %s -o  -silent" % URL_TARGET)

So as a consequence, the script just HANGS WITHOUT ERRORS after the "Opened Ports" scan completes.

Can you have a look at the script I sent and help me figure out why pls.

Thanks.

**Comment by doncalli** [comment]
Cache-Bounty,
You have to compile and install nmap on your system (go to nmap.org for more details). It looks like it is a prerequisite for the script to run as there are NMAP commands which execute within the script
